server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: dept_routh #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址 没有进行负载均衡
          uri: lb://microservicecloud-privider-dept   #匹配后提供服务的路由地址
          predicates:
            - Path=/dept/findByid/** #断言，路径相匹配的进行路由
        - id: dept_routh2 #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://microservicecloud-privider-dept   #匹配后提供服务的路由地址
          predicates:
            - Path=/dept/add/** #断言，路径相匹配的进行路由
            - After=2021-05-10T09:57:39.458+08:00[Asia/Shanghai]    #在该时间之后访问才有效
            - Cookie=username,zzyy       #访问的时候需要用:  http://localhost:9527/dept/add/     --cookie  "username=zzyy"
            - Header=X-Request-Id,  \d+  #请求头要有 X-Request-Id属性并且值为整数的正则表达式 例如： http://localhost:9527/dept/add/  -H "X-Request-Id:123"
            - Method=GET
            - Query=username, \d+   #要有参数名username并且值还要是整数才能路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: # 服务提供者provider注册金eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka