#配置服务器信息
server:
  port: 9002
  #context-path: /study 配置根目录
#数据库信息配置
spring:
  application:
    name: microservicecloud-zuul #应用名称

#客户端注册进eureka服务列表
eureka:
  instance:
    instance-id: microservice-zuul
    prefer-ip-address: true #当鼠标点击到该服务链接上时在网页左下角显示该服务的ip地址
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#设置info内容  注册中心点击该服务连接后 跳转之后显示的内容
zuul:
  #忽略原服务名
  ignored-services: microservicecloud-privider-dept
  routes:
    n0:
      serviceId: microservicecloud-privider-dept
      #起别名
      path: /mydept/*
info:
  app.name: microserviceZuul
  build.artifactId: microservicecloud-zuul
  build.version: 1.0-SNAPSHOT